language: java

jdk: openjdk7

env:
  matrix:
    # test suites to run in parallel
    - TEST_SUITE=travis-junit
    - TEST_SUITE=travis-cpp       BUILD_CLIENT_TESTS=true  SKIP_JNI=true
    - TEST_SUITE=travis-valgrind  BUILD_CLIENT_TESTS=true  SKIP_JNI=true
    - TEST_SUITE=travis-contrib
    - TEST_SUITE=travis-deploy

sudo: false

addons:
  apt:
    packages:
      - libboost-all-dev
      - libfuse-dev
      - fuse
      - libssl-dev
      - libattr1-dev
      - make
      - cmake
      - automake
      - python
      - valgrind
      - net-tools

before_script:
  - TEST_DIR="/tmp/xtreemfs_xtestenv"
  - XTREEMFS_DIR=`pwd`
  - XTREEMFS_DIST_DIR="xtreemfs-${TRAVIS_TAG}-$(lsb_release -c -s)-dist"
  - XTREEMFS_DIST_TAR="${XTREEMFS_DIST_DIR}.tar.gz"

script:
  - make client server hadoop-client -j2
  - ./tests/xtestenv --clean-test-dir -x $XTREEMFS_DIR -t $TEST_DIR -c $XTREEMFS_DIR/tests/test_config.py -p $TEST_SUITE

after_failure:
  - JUNIT_RESULT=`./contrib/travis/parse_results.py $TEST_DIR/result.json 'JUnit tests'`
  - CPP_RESULT=`./contrib/travis/parse_results.py $TEST_DIR/result.json 'C++ Unit Tests'`
  - VALGRIND_RESULT=`./contrib/travis/parse_results.py $TEST_DIR/result.json 'Valgrind memory-leak check for C++ Unit Tests'`
  - CONTRIB_RESULT=`./contrib/travis/parse_results.py $TEST_DIR/result.json 'hadoop adapter junit tests'`
  - if [[ $JUNIT_RESULT = "false" ]]; then cat $TEST_DIR/log/junit.log; fi
  - if [[ $CPP_RESULT = "false" ]]; then cat cpp/build/Testing/Temporary/LastTest.log; fi
  - if [[ $VALGRIND_RESULT = "false" ]]; then cat $TEST_DIR/log/valgrind.log; fi
  - if [[ $CONTRIB_RESULT = "false" ]]; then cat $TEST_DIR_/log/hadoop-*-junit.log; fi

before_deploy:
  - mkdir "${XTREEMFS_DIST_DIR}"
  - make install DESTDIR="${XTREEMFS_DIST_DIR}"
  - tar czf "${XTREEMFS_DIST_TAR}" "${XTREEMFS_DIST_DIR}"

deploy:
  provider: releases
  api_key:
    # robert-schmidtke's encrypted GitHub API key
    secure: "XnC5jy6a6cLMVglnl6KTBkr3o8ir3ulKqKKjc669yUjAET7LfTyGdWcTHsekPxhiUMOnM4mwjna519yrGseTRUE6ff4Ba0FrBDwMK4bXdPyeVnCG59wUndFUTBKlOgFOz3tD4g/ZfdicufnCTRILjCqwDL2U3MNY31LoUssM77o="
  file: "${XTREEMFS_DIST_TAR}"
  skip_cleanup: true
  overwrite: true
  on:
    repo: xtreemfs/xtreemfs
    tags: true
    condition: "$TEST_SUITE = travis-deploy"
